# Generated by Django 4.1.1 on 2022-09-15 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=264, unique=True)),
                ('model_year', models.IntegerField(max_length=4)),
                ('mileage', models.IntegerField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='CUSTOMER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('middle', models.CharField(max_length=264)),
                ('last', models.CharField(max_length=264)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BOOKINGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_1.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_1.customer')),
            ],
        ),
    ]
